#!/usr/bin/env python3
"""
gen_renode_callbacks.py

Companion generator to PeakRDL-renode.

PeakRDL-renode (peakrdl renode ...) emits a *stub* C# partial class: registers
and fields with the right widths/offsets, but no behavior -- no
ValueProviderCallback / WriteCallback wiring.

This script compiles the same .rdl file with the systemrdl-compiler and walks
the elaborated register model to emit the *second* file: a partial class
(same class/namespace) whose Init() method wires up:

  - a ValueProviderCallback for every field whose `sw` access is `r` or `rw`
    (software can read it -> we need to supply the value)
  - a WriteCallback for every field whose `sw` access is `w` or `rw`
    (software can write it -> we need to capture/store the value)

The default callback bodies just read/write a backing `Value` on the field
itself (mirroring the example you supplied). That's a reasonable default for
plain storage registers; anything with real side effects (triggering an
action, clearing-on-read, etc.) you'll edit by hand afterwards -- this script
gets you the boilerplate wiring so you don't have to type it for every
field in a large peripheral.

Usage:
    python3 gen_renode_callbacks.py peripheral.rdl \\
        -n SMPH \\
        -N Antmicro.Renode.Peripherals.Example_Registers \\
        -o SMPH_callbacks.cs

Requires:
    pip install systemrdl-compiler
"""

import argparse
import sys
from systemrdl import RDLCompiler, RDLCompileError
from systemrdl.node import AddrmapNode, RegNode, FieldNode


def pascal_case(name: str) -> str:
    """
    Match PeakRDL-renode's register property naming: "REG0" -> "Reg0".
    This mirrors Python's str.capitalize() behaviour, which is what the
    stub generator's naming convention reduces to for all-caps identifiers.
    """
    if not name:
        return name
    return name[0].upper() + name[1:].lower()


def sw_access(field: FieldNode) -> str:
    """Return the field's sw access as one of 'r', 'w', 'rw', 'na'."""
    access = field.get_property('sw')
    return access.name.lower() if hasattr(access, 'name') else str(access).lower()


def iter_regs(node):
    """Yield every RegNode under an addrmap/regfile node, recursively."""
    for child in node.children():
        if isinstance(child, RegNode):
            yield child
        elif not isinstance(child, FieldNode):
            # regfile / nested addrmap -- recurse
            yield from iter_regs(child)


def build_field_block(reg_prop: str, field_name: str, access: str, indent: str) -> str:
    """Build the C# block wiring callbacks for a single field."""
    lines = []
    field_ref = f"this.{reg_prop}.{field_name}"

    if access in ('r', 'rw'):
        lines.append(f"{indent}{field_ref}.ValueProviderCallback += (_) =>")
        lines.append(f"{indent}{{")
        lines.append(f"{indent}    return {field_ref}.Value;")
        lines.append(f"{indent}}};")

    if access in ('w', 'rw'):
        if lines:
            lines.append("")
        lines.append(f"{indent}{field_ref}.WriteCallback += (oldval, newval) =>")
        lines.append(f"{indent}{{")
        lines.append(f"{indent}    {field_ref}.Value = (uint)newval;")
        lines.append(f"{indent}}};")

    return "\n".join(lines)


def build_cs_file(top_node: AddrmapNode, class_name: str, namespace: str, rdl_filename: str) -> str:
    indent = "            "  # 12 spaces, matches the sample's nesting depth
    body_parts = []

    regs = list(iter_regs(top_node))
    if not regs:
        print("Warning: no registers found in the elaborated design.", file=sys.stderr)

    for i, reg in enumerate(regs):
        reg_prop = pascal_case(reg.inst_name)
        field_blocks = []

        for field in reg.fields():
            access = sw_access(field)
            if access == 'na':
                continue
            field_blocks.append(
                build_field_block(reg_prop, field.inst_name, access, indent)
            )

        if not field_blocks:
            continue

        body_parts.append("\n\n".join(field_blocks))

    body = "\n\n\n".join(body_parts)

    return f'''\
// Generated by gen_renode_callbacks.py from {rdl_filename}
// Companion callback file for the PeakRDL-renode stub -- do not regenerate
// over hand-written edits without diffing first.
using Antmicro.Renode.Time;
using Antmicro.Renode.Core;
using Antmicro.Renode.Core.Structure.Registers;
using Antmicro.Renode.Peripherals.Bus;
using Antmicro.Renode.Peripherals.Timers;
using Antmicro.Renode.Utilities;
using System.Linq;
using System.Collections.Generic;
using Antmicro.Renode.Logging;
using System.IO;
using System.Threading;
using System;

namespace {namespace} // This namespace name will be given by the user
{{
    public partial class {class_name} : IProvidesRegisterCollection<DoubleWordRegisterCollection>, IPeripheral, IDoubleWordPeripheral, INumberedGPIOOutput, IGPIOReceiver
    {{
        partial void Init()
        {{
            this.Log(LogLevel.Info, "Example peripheral constructor");
{body}
        }}
    }}
}}
'''


def main():
    parser = argparse.ArgumentParser(description=__doc__, formatter_class=argparse.RawDescriptionHelpFormatter)
    parser.add_argument("rdl_file", help="Path to the .rdl input file")
    parser.add_argument("-n", "--name", required=True, dest="class_name",
                         help="Peripheral/class name (should match the -n passed to `peakrdl renode`)")
    parser.add_argument("-N", "--namespace", required=True,
                         help="C# namespace (should match the -N passed to `peakrdl renode`)")
    parser.add_argument("-o", "--output", required=True, help="Output .cs file path")
    parser.add_argument("--top", default=None, help="Top-level addrmap name, if the file defines more than one")
    args = parser.parse_args()

    rdlc = RDLCompiler()
    try:
        rdlc.compile_file(args.rdl_file)
        root = rdlc.elaborate(top_def_name=args.top) if args.top else rdlc.elaborate()
    except RDLCompileError:
        sys.exit(1)

    top_node = root.top

    cs_text = build_cs_file(top_node, args.class_name, args.namespace, args.rdl_file)

    with open(args.output, "w") as f:
        f.write(cs_text)

    print(f"Wrote {args.output}")


if __name__ == "__main__":
    main()
